sudo: true
dist: xenial
language: minimal

services:
  - redis-server

install:
  - sudo apt-get purge wireless-regdb
  - sudo rm -f /etc/apt/sources.list.d/*
  - echo "deb http://httpredir.debian.org/debian/ stretch main" |sudo tee /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get dist-upgrade -y --allow-unauthenticated
  - make build-depends

script:
  - make
