sudo: true
dist: xenial
language: minimal

services:
  - redis-server

install:
  - sudo apt-get update
  - make build-depends-xenial
  - wget http://http.us.debian.org/debian/pool/main/d/django-redis/python3-django-redis_4.7.0-1_all.deb
  - sudo dpkg -i python3-django-redis*.deb

script:
  - make
