sudo: true
dist: xenial
language: python

python:
  - 3.6

services:
  - redis-server

install:
  - sudo apt-get update
  - make build-depends-xenial
  - pip install django-redis>=4.7.0 pytest-cov>=2.4.0

script:
  - make
