sudo: true
dist: xenial
language: python

python:
  - 3.6

services:
  - redis-server

install:
  - sudo apt-get update
  - make build-depends; true
  - pip install django-redis>=4.7.0

script:
  - make
